export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";

export const GET_LOAN_LIST_SUCCESS = "GET_LOAN_LIST_SUCCESS";
export const LOADING_LOAN_LIST = "LOADING_LOAN_LIST";